// Generated by CoffeeScript 1.3.3
(function() {

  this.PicassaAdPhoto = (function() {

    function PicassaAdPhoto(elem) {
      this.url = elem.href.replace(/alt=rss/, 'alt=json');
      this.pos = $(elem).position();
      $('#ad-gallery-container').on('click', 'a.close', function() {
        return $('#ad-gallery-container').hide();
      });
    }

    PicassaAdPhoto.prototype.createGallery = function() {
      var _this = this;
      return $.getJSON(this.url, function(resp) {
        return _this.createHTML(resp);
      });
    };

    PicassaAdPhoto.prototype.createHTML = function(data) {
      var arr, photo, photos, _i, _len;
      photos = data.feed.entry;
      arr = ['<a href="javascript:" class="close" title="Cerrar"></a>', '<div class="ad-gallery"><div class="ad-image-wrapper"></div><div class="ad-controls"></div>', '<div class="ad-nav"><div class="ad-thumbs"><ul class="ad-thumb-list">'];
      for (_i = 0, _len = photos.length; _i < _len; _i++) {
        photo = photos[_i];
        arr.push(['<li>', "<a href='" + photo.content.src + "'>", this.createImage(photo), "</a>", '</li>'].join(''));
      }
      arr.push('</ul></div></div></div></div>');
      $('#ad-gallery-container').html(arr.join('')).show().css({
        top: this.pos.top - 200,
        left: this.pos.left
      });
      return $('.ad-gallery').adGallery({
        loader_image: 'css/loader.gif',
        start_at_index: 0,
        slideshow: {
          start_label: 'Iniciar',
          stop_label: 'Parar'
        }
      });
    };

    PicassaAdPhoto.prototype.createImage = function(photo) {
      var media, thumb;
      media = photo.media$group;
      thumb = media.media$thumbnail[0].url;
      if (media.media$description.$t === '') {
        return "<img src ='" + thumb + "' />";
      } else {
        return "<img src ='" + thumb + "' title='" + media.media$description.$t + "' />";
      }
    };

    return PicassaAdPhoto;

  })();

}).call(this);


$(function() {
  $('a').click(function() {
    if(this.href.match(/picasaweb/) && this.href.match(/alt=rss/)) {
      photo = new PicassaAdPhoto(this);
      photo.createGallery();
      return false;
    }
  })
});
